version: 2
kind: Application
name: claims-pipeline-app

pipeline:
  - signature: claims
    model: claims-preprocessing:1
  - signature: claims
    monitoring:
      - name: ks
        input: feature_42
        type: Kolmogorov-Smirnov
        healthcheck:
          enabled: true
          treshold: 69
      - name: gan
        input: feature
        type: GAN
        app: claims-autoencoder-app
        healthcheck:
          enabled: true
          treshold: 69
      - name: autoencoder
        input: feature
        type: Autoencoder
        app: claims-autoencoder-app
        healthcheck:
          enabled: true
          treshold: 69
    model-variants:
      - model: claims-model:1
        weight: 80
      - model: claims-model:2
        weight: 20